/**
 * Codegen for `@streamboard/sdk`. Turns a board's schema document
 * (`Streamboard.schema()` / `GET …/schema`) into a typed
 * `StreamboardState` interface plus thin typed `push()` / `pull()`
 * wrappers, so worker code gets compile-time checks on the envelope it
 * pushes — no LLM in the runtime path.
 *
 *     streamboard-codegen --token sb_d_… -o streamboard.generated.ts
 *
 * The folding logic (dotted `$bind` paths → nested interfaces) is
 * vendored from `cli/src/lib/bind-paths.ts` in this repo, which in turn
 * mirrors `packages/streamboard/src/extract-bind-paths.ts` in the
 * private monorepo. Keep the three in sync if the slot-type table
 * changes; tests pin the mirror.
 */

import type { SchemaField, SchemaResult } from "./index"

/** Minimal shape `buildStateInterfaceBody` needs from a schema field. */
type CodegenField = Pick<SchemaField, "path" | "tsType">

/**
 * Build a nested interface body from flat dotted paths. Paths like
 * `kpis.mrr.value` fold into `{ kpis: { mrr: { value: … } } }`. Returns
 * the body only (no enclosing `interface X { … }` — the caller adds
 * that). An empty field set yields an open index signature so a
 * freshly-minted board with no binds still typechecks.
 */
export function buildStateInterfaceBody(fields: CodegenField[]): string {
  if (fields.length === 0) return "  [key: string]: unknown\n"

  type Node = { children: Map<string, Node>; tsType?: string }
  const root: Node = { children: new Map() }

  for (const field of fields) {
    const segments = field.path.split(".")
    let node = root
    for (let i = 0; i < segments.length - 1; i++) {
      const seg = segments[i]
      if (!seg) continue
      let child = node.children.get(seg)
      if (!child) {
        child = { children: new Map() }
        node.children.set(seg, child)
      }
      node = child
    }
    const leaf = segments[segments.length - 1]
    if (!leaf) continue
    const existing = node.children.get(leaf)
    if (existing) {
      // Path collision (a parent of a deeper path also carries its own
      // bind, e.g. both `kpis.mrr` and `kpis.mrr.value`). Keep the
      // deeper structure; mark the parent leaf `unknown` so the output
      // still compiles. Well-formed specs don't hit this — the API
      // layer surfaces the conflict warning.
      existing.tsType = "unknown"
    } else {
      node.children.set(leaf, { children: new Map(), tsType: field.tsType })
    }
  }

  return renderNode(root, 1)
}

function renderNode(
  node: { children: Map<string, { children: Map<string, unknown>; tsType?: string }> },
  depth: number,
): string {
  const indent = "  ".repeat(depth)
  const lines: string[] = []
  for (const [name, child] of node.children) {
    const safe = isValidIdentifier(name) ? name : JSON.stringify(name)
    if (child.tsType && child.children.size === 0) {
      lines.push(`${indent}${safe}: ${child.tsType}`)
    } else {
      lines.push(`${indent}${safe}: {`)
      lines.push(
        renderNode(
          child as Parameters<typeof renderNode>[0],
          depth + 1,
        ),
      )
      lines.push(`${indent}}`)
    }
  }
  return lines.join("\n")
}

function isValidIdentifier(name: string): boolean {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name)
}

/** Default API base baked into generated push/pull helpers. */
const DEFAULT_BASE_URL = "https://usestreamboard.com"

/**
 * Render a self-contained `.ts` module for a board: the typed
 * `StreamboardState` interface plus `push()` / `pull()` helpers that
 * wrap `@streamboard/sdk` and read `STREAMBOARD_TOKEN` from the
 * environment by default.
 */
export function generate(
  doc: Pick<SchemaResult, "streamboardId" | "version" | "fields">,
  options: { baseUrl?: string } = {},
): string {
  const baseUrl = (options.baseUrl ?? DEFAULT_BASE_URL).replace(/\/$/, "")
  const body = buildStateInterfaceBody(doc.fields ?? [])
  return `// Generated by \`streamboard-codegen ${doc.streamboardId}\`.
// Do not edit by hand — re-run codegen after the spec mints a new version.
//
// Source: ${baseUrl}/api/data/v1/streamboards/${doc.streamboardId}/schema
// Streamboard version: ${doc.version}

import {
  Streamboard,
  type PullOptions,
  type PullResult,
  type PushOptions,
  type PushResult,
} from "@streamboard/sdk"

/** State envelope shape for this streamboard. Derived from the spec's bindable slots. */
export interface StreamboardState {
${body}}

/**
 * Push a typed state envelope. Reads STREAMBOARD_TOKEN from
 * \`process.env\` by default; pass \`options.token\` to override
 * (e.g. when the caller resolves the token from a secrets store).
 */
export async function push(
  state: StreamboardState,
  options: PushOptions & { token?: string; baseUrl?: string } = {},
): Promise<PushResult> {
  const token = options.token ?? process.env.STREAMBOARD_TOKEN
  if (!token) {
    throw new Error(
      "Missing STREAMBOARD_TOKEN — set it in the environment or pass options.token.",
    )
  }
  const board = new Streamboard<StreamboardState>({
    token,
    baseUrl: options.baseUrl ?? ${JSON.stringify(baseUrl)},
  })
  const { token: _token, baseUrl: _baseUrl, ...rest } = options
  return board.push(state, rest)
}

/**
 * Read the current typed state envelope. Same auth surface as
 * \`push()\`. The server returns \`state: {}\` when no push has ever
 * happened — the StreamboardState type stays optional-friendly so
 * top-level reads after a fresh mint still typecheck.
 */
export async function pull(
  options: PullOptions & { token?: string; baseUrl?: string } = {},
): Promise<PullResult<StreamboardState>> {
  const token = options.token ?? process.env.STREAMBOARD_TOKEN
  if (!token) {
    throw new Error(
      "Missing STREAMBOARD_TOKEN — set it in the environment or pass options.token.",
    )
  }
  const board = new Streamboard<StreamboardState>({
    token,
    baseUrl: options.baseUrl ?? ${JSON.stringify(baseUrl)},
  })
  const { token: _token, baseUrl: _baseUrl, ...rest } = options
  return board.pull(rest)
}
`
}
