"""Generate typed `StreamboardState` TypedDicts from a board's schema.

    streamboard-codegen --token sb_d_… -o state_types.py

Fetches GET /api/data/v1/streamboards/<id>/schema, folds the dotted
`$bind` paths into nested objects, and emits a TypedDict module you can
import to type the dict you pass to `Streamboard.push()`.
"""

from __future__ import annotations

import argparse
import os
import sys
from typing import Any

from .client import Streamboard

_SCALARS = {
    "string": "str",
    "number": "float",
    "integer": "int",
    "boolean": "bool",
    "null": "None",
}


def _pascal(parts: list[str]) -> str:
    out = "".join(p[:1].upper() + p[1:] for p in parts if p)
    cleaned = "".join(ch if ch.isalnum() else "_" for ch in out)
    return cleaned or "Field"


def _fold(properties: dict[str, Any]) -> dict[str, Any]:
    """Dotted keys → nested tree. Leaves stay JSON-Schema nodes."""
    tree: dict[str, Any] = {}
    for path, node in properties.items():
        cur = tree
        segs = path.split(".")
        for seg in segs[:-1]:
            cur = cur.setdefault(seg, {})  # type: ignore[assignment]
        cur[segs[-1]] = node
    return tree


def _py_type(node: Any, name_parts: list[str], emitted: list[str]) -> str:
    """Map a JSON-Schema node to a Python annotation.

    Nested objects emit their own TypedDict (post-order, into
    `emitted`) so a parent can reference an already-defined name.
    """
    if not isinstance(node, dict):
        return "Any"
    enum = node.get("enum")
    if isinstance(enum, list) and enum:
        lits = ", ".join(repr(v) for v in enum)
        return f"Literal[{lits}]"
    jtype = node.get("type")
    if jtype == "array":
        item = _py_type(node.get("items", {}), [*name_parts, "Item"], emitted)
        return f"list[{item}]"
    if jtype == "object" or "properties" in node:
        props = node.get("properties")
        if isinstance(props, dict) and props:
            return _emit_typeddict(props, name_parts, emitted)
        return "dict[str, Any]"
    if isinstance(jtype, str) and jtype in _SCALARS:
        return _SCALARS[jtype]
    return "Any"


def _emit_typeddict(
    properties: dict[str, Any], name_parts: list[str], emitted: list[str]
) -> str:
    cls = _pascal(name_parts) or "StreamboardState"
    lines = []
    for key, child in properties.items():
        if isinstance(child, dict) and "type" not in child and "enum" not in child:
            # Branch produced by _fold (nested dotted path) — synthesise an
            # object node so it recurses into a nested TypedDict.
            child = {"type": "object", "properties": child}
        ann = _py_type(child, [*name_parts, key], emitted)
        lines.append(f"    {key}: {ann}")
    body = "\n".join(lines) if lines else "    pass"
    emitted.append(f"class {cls}(TypedDict, total=False):\n{body}\n")
    return cls


def generate(schema_doc: dict[str, Any]) -> str:
    js = schema_doc.get("jsonSchema", {})
    properties = js.get("properties", {})
    folded = _fold(properties) if isinstance(properties, dict) else {}
    emitted: list[str] = []
    _emit_typeddict(folded, ["StreamboardState"], emitted)
    header = (
        '"""Generated by streamboard-codegen — do not edit by hand.\n\n'
        f"Source: {schema_doc.get('streamboardId', '?')} "
        f"@ version {schema_doc.get('version', '?')}\n"
        '"""\n\n'
        "from __future__ import annotations\n\n"
        "from typing import Any, Literal, TypedDict\n\n"
    )
    return header + "\n".join(emitted)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="streamboard-codegen")
    p.add_argument(
        "--token",
        default=os.environ.get("STREAMBOARD_TOKEN"),
        help="sb_d_<id>_<secret> (or env STREAMBOARD_TOKEN)",
    )
    p.add_argument("--id", dest="sid", default=None, help="override board id")
    p.add_argument("--base-url", default="https://usestreamboard.com")
    p.add_argument("-o", "--out", default=None, help="output file (default: stdout)")
    args = p.parse_args(argv)
    if not args.token:
        p.error("--token or STREAMBOARD_TOKEN is required")

    with Streamboard(token=args.token, base_url=args.base_url) as board:
        doc = board.schema(streamboard_id=args.sid)
    code = generate(doc)

    if args.out:
        with open(args.out, "w", encoding="utf-8") as fh:
            fh.write(code)
        print(f"wrote {args.out}", file=sys.stderr)
    else:
        sys.stdout.write(code)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
